FROM sonarqube:9.2.2-developer
USER root
RUN apk add --no-cache wget curl java-cacerts jq postgresql-client
RUN ln -sf /etc/ssl/certs/java/cacerts /usr/lib/jvm/java-11-openjdk/lib/security/cacerts
ADD ./plugins /tmp/plugins
RUN rm -rf ./extensions/plugins/* && \
    cat /tmp/plugins/plugin-list && \
    chmod +x /tmp/plugins/install-plugins.sh && \
    ls /tmp/plugins -l && \
    /tmp/plugins/install-plugins.sh
WORKDIR /opt/sonarqube
COPY ./start-with-profile.sh .
ADD ./rules /tmp/rules
ADD sonar.properties /opt/sonarqube/conf/sonar.properties
RUN chown -R sonarqube:sonarqube . && chmod +x start-with-profile.sh
USER sonarqube
CMD ["./start-with-profile.sh"]
