  www:
    build: .
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    links:
      - db
    ports:
      - "9000:9000"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data