version: '3'

services:
  www:
      image: ictu/sonar:latest
      environment:
          - SONARQUBE_JDBC_USERNAME=sonar
          - SONARQUBE_JDBC_PASSWORD=sonar-password
          - "SONARQUBE_JDBC_URL=jdbc:mysql://db/sonar?useUnicode=true&amp;characterEncoding=utf8"
      links:
          - db
  db:
      image: mysql:5.6
      environment:
          - MYSQL_ROOT_PASSWORD=root-password
          - MYSQL_DATABASE=sonar
          - MYSQL_USER=sonar
          - MYSQL_PASSWORD=sonar-password
      volumes:
          - /db/var/lib/mysql:/var/lib/mysql