FROM sonarqube:8.3.1-developer
USER root
RUN apk add --no-cache wget curl jq
ADD ./plugins /tmp/plugins
RUN rm -rf ./extensions/plugins/* && \
    cat /tmp/plugins/plugin-list && \
    chmod +x /tmp/plugins/install-plugins.sh && \
    ls /tmp/plugins -l && \
    /tmp/plugins/install-plugins.sh
WORKDIR /opt/sonarqube
COPY ./start-with-profile.sh .
ADD ./rules /tmp/rules
RUN chown -R sonarqube:sonarqube . && chmod +x start-with-profile.sh
USER sonarqube
CMD ["./start-with-profile.sh"]
