version: 2

jobs:
  build_and_push_tag:
    machine: true
    parallelism: 4
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            docker build -f Dockerfile-community-edition -t ictu/sonar:${CIRCLE_TAG} .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/sonar:${CIRCLE_TAG}
  build_and_push_de_tag:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            docker build -f Dockerfile-developer-edition -t ictu/sonar:${CIRCLE_TAG} .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/sonar:${CIRCLE_TAG}

workflows:
  version: 2
  build_and_push:
    parallelism: 4
    jobs:
      - build_and_push_tag:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+(\.[0-9])*(-[0-9]+)*$/
            branches:
              ignore: /.*/
      - build_and_push_de_tag:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+(\.[0-9])*(-[0-9]+)*-developer$/
            branches:
              ignore: /.*/
