---
services:
  www:
    environment:
      SONAR_JDBC_USERNAME: "sonar_user"
      SONAR_JDBC_PASSWORD: "sonar_pass"
      SONARQUBE_PASSWORD: "Admin1234..."
      PROJECT_CODE: "PROJ1"
      PROJECT_RULES: "+csharpsquid:S104;-typescript:S1301;+Web:UnclosedTagCheck"

  db:
    environment:
      POSTGRES_USER: "sonar_user"
      POSTGRES_PASSWORD: "sonar_pass"
