---
services:
  www:
    build:
      context: ..
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://db:5432/sonar"
    ports:
      - mode: ingress
        target: 9000
        published: 9001
    volumes:
      - type: "volume"
        source: "plugins"
        target: "/opt/sonarqube/extensions/plugins"
    depends_on:
      - db

  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_DB: "sonar"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - "dbdata:/var/lib/postgresql/data:rw"

volumes:
  dbdata:
  plugins:
