---
apiVersion: v2
name: ictu-sonarqube
version: 1.0.0
appVersion: "10.5.1"
description: A SonarQube helm chart with plugins, profiles and config used at ICTU
type: application
home: https://github.com/ICTU/sonar
dependencies:
  - name: postgresql
    version: 15.2.2  # appVersion 16.2.0
    repository: https://charts.bitnami.com/bitnami  # TODO - 3rd party helm chart or postgres docker container? NB: sonar defines bitnami postgres 10.15.0 as a dependency
  - name: sonarqube
    version: 10.5.1
    repository: https://SonarSource.github.io/helm-chart-sonarqube
