---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgresql-secret
  labels:
    app: sonarqube
    release: sonarqube
data:
  sonar_db_password: ""
  postgres_db_password: ""
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube-secret
  labels:
    app: sonarqube
    release: sonarqube
data:
  SONARQUBE_USERNAME: ""
  SONARQUBE_PASSWORD: ""
type: Opaque
