---
name: Publish container images to Docker Hub

on: workflow_dispatch  # Only triggered manually, must be done from a semantic version tag

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: semver
        name: Ensure that selected tag is a semantic version
        uses: matt-usurp/validate-semver@v2
        with:
          version: ${{ github.ref }}

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Package and push container to Docker Hub
        if: ${{ github.ref_type == 'tag' }}
        run: |
          export CONTAINER_TAG="${{ steps.semver.outputs.version }}-developer"
          docker build -t ictu/sonar:${CONTAINER_TAG} .
          docker push ictu/sonar:${CONTAINER_TAG}
