---
name: Publish container images to Docker Hub

on: workflow_dispatch  # Only triggered manually, must be done from a semantic version tag

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          persist-credentials: false

      - id: semver
        name: Ensure that selected tag is a semantic version
        uses: matt-usurp/validate-semver@v3.0.0
        with:
          version: ${{ github.ref }}

      - uses: docker/login-action@v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Package and push container to Docker Hub
        if: ${{ github.ref_type == 'tag' }}
        run: |
          export CONTAINER_TAG="${STEPS_SEMVER_OUTPUTS_VERSION}-developer"
          docker build -t ictu/sonar:${CONTAINER_TAG} .
          docker push ictu/sonar:${CONTAINER_TAG}
        env:
          STEPS_SEMVER_OUTPUTS_VERSION: ${{ steps.semver.outputs.version }}
