---
name: Release Helm chart

on: workflow_dispatch  # Only triggered manually

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Package and push Helm chart to Docker Hub
        run: |
          cd helm
          helm dependency build .
          helm package .
          helm push ictu-sonarqube-*.tgz oci://registry-1.docker.io/ictu
